name: ${project.artifactId}
main: org.wargamer2010.signshop.SignShop
version: ${project.version}
dev-url: http://dev.bukkit.org/server-mods/signshop
authors: [Wargamer2010, Devinish, Jannyboy11]
softdepend: [Vault, Multiverse-Core, ShowCaseStandalone, Deadbolt, Notifications, dynmap, Towny, WhatIsIt]
load: POSTWORLD
api-version: "1.14"
commands:
  signshop:
    description: Admin commands for SignShop
    usage: /signshop [reload|stats|version|about|help|sign|tutorial]
